%% SimuGen Example: Series Hybrid Vehicle
%
% This is the example that started it all — a complete series hybrid
% vehicle powertrain with energy management.
%
% Usage:
%   addpath(genpath('../src'));
%   setenv('ANTHROPIC_API_KEY', 'your-key');
%   ex_hybrid_vehicle

description = [...
    'Create a series hybrid vehicle model with the following subsystems: ' ...
    '' ...
    '1. Speed Control Loop: ' ...
    '- Constant block for reference speed (from workspace variable Cycle via timeseries) ' ...
    '- Sum block computing speed error (reference - actual) ' ...
    '- PID controller (P=400, I=40, D=0) ' ...
    '' ...
    '2. Vehicle Dynamics: ' ...
    '- Torque and Power limits MATLAB Function (limits motor torque based on speed) ' ...
    '- Motor response MATLAB Function (applies drivetrain efficiency) ' ...
    '- Brake control MATLAB Function (splits braking force) ' ...
    '- Longitudinal dynamics subsystem with drag, rolling resistance, and integrator for speed ' ...
    '' ...
    '3. Energy Management: ' ...
    '- Hamiltonian minimization MATLAB Function (decides generator ON/OFF based on lambda) ' ...
    '- ICE response MATLAB Function (computes generator power and fuel consumption) ' ...
    '' ...
    '4. Battery: ' ...
    '- Power balance (motor power + generator power + auxiliary) ' ...
    '- SoC integrator with saturation between 0 and 1 ' ...
    '' ...
    'Add To Workspace blocks for speed, SoC, generator power, and fuel power. ' ...
    'Vehicle mass = 1330 kg, tire radius = 0.335 m, frontal area = 2.22 m^2, Cd = 0.23.'];

simugen(description, 'ModelName', 'hybrid_vehicle', 'Open', true);
