%% SimuGen Example: Mass-Spring-Damper System
%
% A simple mechanical system to demonstrate basic SimuGen usage.
%
% Usage:
%   addpath(genpath('../src'));
%   setenv('ANTHROPIC_API_KEY', 'your-key');
%   ex_mass_spring_damper

description = [...
    'Create a mass-spring-damper system. ' ...
    'Mass m=1 kg, spring constant k=10 N/m, damping coefficient c=0.5 N.s/m. ' ...
    'Apply a step force of 1 N at t=0. ' ...
    'The equation of motion is: m*x_ddot + c*x_dot + k*x = F. ' ...
    'Use two Integrator blocks for velocity and position. ' ...
    'Include a Scope to display position vs time. ' ...
    'Add To Workspace block for position output.'];

simugen(description, 'ModelName', 'mass_spring_damper', 'Open', true);
