%% SimuGen Example: PID Controller for DC Motor
%
% This example generates a Simulink model of a PID-controlled DC motor.
%
% Usage:
%   addpath(genpath('../src'));
%   setenv('ANTHROPIC_API_KEY', 'your-key');
%   ex_pid_controller

description = [...
    'Create a PID speed controller for a DC motor. ' ...
    'The motor has inertia J=0.01 kg.m^2 and damping coefficient b=0.1 N.m.s. ' ...
    'The motor torque constant is Kt=0.01 N.m/A and back-EMF constant Ke=0.01 V.s/rad. ' ...
    'Motor resistance R=1 ohm and inductance L=0.5 H. ' ...
    'Use a Step input for desired speed (from 0 to 1 rad/s at t=1s). ' ...
    'Add a PID controller with P=100, I=200, D=10. ' ...
    'Include Scope blocks to monitor speed and current. ' ...
    'Add To Workspace blocks for speed and time.'];

simugen(description, 'ModelName', 'dc_motor_pid', 'Open', true);
